### ISSUE TITLE
If the same file twice is introduced, whether it should warn the user

### ISSUE THREAD

**Issue by fsy0718** [jonathantneal/postcss-partial-import#10]
I have 3 files:
- A  define some placeholder,example:

```
  @define-placeholder test {
     color: red;
  }
```
- B  import A and extend some placeholder, example:

```
  .test {
    @extend test;
   }
```
- C import A and B, this file is the master file; when i complete the gulp task, it has two `.test`

```
.test{color: red}
.test{color: red}
```

When I removed the import A from B, It's work right;

**Comment by jonathantneal** [comment]
postcss-partial import is now a layer of sugar atop postcss-import, so duplicate files are now skipped by default.
