### ISSUE TITLE
How do we import styles in node_modules?

### ISSUE THREAD

**Issue by rodoabad** [jonathantneal/postcss-partial-import#17]
Would this be possible in the future?

`@import 'package-name';`

Instead of

`@import '../../../node_modules/package-name'`

**Comment by medeeiros** [comment]
yes please

**Comment by rNoz** [comment]
+1. It will be great by providing alternative "root" paths (`["node_modules", "bower_components"]`) in options.

**Comment by daveaspinall** [comment]
I'm using [postcss-import](https://github.com/postcss/postcss-import) to import my bower partials right before `precss` inlines them (using `postcss-partial-import`). It has a `path` option where you can define your `bower_components` directory:

```
var postcss = require('gulp-postcss');
var cssImport = require('postcss-import');
var scss  = require('postcss-scss');
var precss = require('precss');

var loadPath = '/bower_components';

gulp.task('css', function() {
    var processors = [
        cssImport({
            path: [loadPath]
        }),
        precss
    ];
    return gulp.src('/css/src/*.css')
        .pipe(postcss(processors), { syntax: scss })
        .pipe(gulp.dest('/css/dist'));
});
```

Hope this helps!

**Comment by jonathantneal** [comment]
This is in PR right now. https://github.com/jonathantneal/postcss-partial-import/pull/19

**Comment by daveaspinall** [comment]
Thanks for adding support for `node_modules`! It doesn't seem to sniff out `bower_components` though. Is that on the horizon at all?

**Comment by jonathantneal** [comment]
This has been added in 2x!
