### ISSUE TITLE
Latest version 2.0.0 doesn't work with latest PostCSS 5.1.2

### ISSUE THREAD

**Issue by akella** [jonathantneal/postcss-partial-import#23]
It parses everything ok, just doesnt replace @imports.
Here is a testcase
http://take.ms/qUK5L 
if i just do 'npm i gulp postcss gulp-postcss postcss-partial-import'
which installs latest versions, imports will not work.

Works ok with PostCSS 5.0.10

**Comment by yuchuanxi** [comment]
+1
now, I used v1.3.0, but it could't automatic recompile on changes to an imported file when using something like webpack’s watch mode.



**Comment by Avol-V** [comment]
I agree, it didn't work at all. So sad, `dir` option is very useful.

**Comment by jonathantneal** [comment]
Are you still having this issue?

**Comment by Avol-V** [comment]
With version 2.1.0 it now works, but if I try to include file, that did not exists, it just ignore this include and leave it as is, when in version 1.3.0 it throws an error “no such file or directory”.

**Comment by jonathantneal** [comment]
postcss-partial import is now a layer of sugar atop the new postcss-import, so this should be resolved.
