### ISSUE TITLE
Synchronous version

### ISSUE THREAD

**Issue by plusbpm** [jonathantneal/postcss-partial-import#25]
Is it possible to create a synchronized version of the module? For use with the server require hook. Or, as an option to add the appropriate option ...

**Comment by TrySound** [comment]
Sync version of postcss generating is only for debug. And you should find another way to transpile before run. Server has middlewares. They're async.

**Comment by plusbpm** [comment]
Unfortunately, there is no possibility to use middleware, it is a server-side rendering html markup with syntax ES6.

**Comment by TrySound** [comment]
Then precompile your assets. This will prevent server overworking,

**Comment by jonathantneal** [comment]
This plugin should **not** be synchronous.
