### ISSUE TITLE
how to watch files change when used with postcss-cli -w

### ISSUE THREAD

**Issue by zyy7259** [jonathantneal/postcss-partial-import#27]
When used with [postcss-cli](https://github.com/postcss/postcss-cli), how to watch file changes.

`postcss-cli` support `postcss-import` with the following config:

``` js
{
  "postcss-import": {
    onImport: function(sources) {
      global.watchCSS(sources, this.from);
    }
  }
}
```

Is there a similar method? I found there is an option `addDependencyTo`, can it be used with `postcss-cli`?

**Comment by jonathantneal** [comment]
postcss-partial import is now a layer of sugar atop postcss-import, so this feature is now available. However, note that addDependencyTo is being deprecated for a new method of tracking files. Please see their documentation.
