### ISSUE TITLE
Use processors for subprocess

### ISSUE THREAD

**Issue by VitaliyR** [jonathantneal/postcss-partial-import#29]
Hello there.

Plugin allows you to apply some postcss-plugins on subprocessor via `config.plugins`. By default, it equals empty array - why? Why it not takes parent processors? 

e.g.:

``` javascript
const pkg = require('./package.json');
this.plugins = opts.plugins || result.processor.plugins.filter(p => p.postcssPlugin !== pkg.name);
```

**Comment by VitaliyR** [comment]
I tested it - it works as it actually should be. Maybe there is a need to add some parameter to config which would do it?

**Comment by VitaliyR** [comment]
Any news on it?

**Comment by jonathantneal** [comment]
postcss-partial import is now a layer of sugar atop postcss-import, so this feature is now available.
