### ISSUE TITLE
postcss-import: Node#moveAfter was deprecated. Use Node#after.

### ISSUE THREAD

**Issue by lmihaidaniel** [jonathantneal/postcss-partial-import#39]
The package `postcss-import` throws some erros like:

`Node#moveAfter was deprecated. Use Node#after.`
`Node#before is deprecated. Use Node#raws.before`

This is fixed in postcss-import@9.1.0

Can someone update the dependency version ?

**Comment by jonathantneal** [comment]
I’m looking into it presently. A simply update of postcss and postcss-import was not enough to resolve the issue.

**Comment by jonathantneal** [comment]
I still see a warning about this, but the dependency has been updated and 4.0.0 has been published.
