### ISSUE TITLE
Path to find

### ISSUE THREAD

**Issue by TrySound** [jonathantneal/postcss-partial-import#5]
Additional option with paths like https://github.com/postcss/postcss-import#path

**Comment by wmadden** [comment]
+1, it would be really helpful if `@import` statements were resolved against an array of paths

**Comment by jonathantneal** [comment]
Great idea. Sorry I didn’t catch this before.

**Comment by aziz** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by jonathantneal** [comment]
This has been added in v2 :)
